/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import Logica.LogicaCliente;
import Logica.LogicaFactura;
import Logica.LogicaOrdenCompra;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Util.println;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import persistencia.Factura;
import persistencia.OrdenCompra;

/**
 *
 * @author francoesteban
 */
public class FrameIngresarFactura extends javax.swing.JFrame {

    /**
     * Creates new form FrameIngresarFactura
     */
    
    JFrame frameInicio;
    
    public FrameIngresarFactura(JFrame frameInicio) {
        this.frameInicio = frameInicio;
        initComponents();
        try {
            cargarDatos();
        } catch (ParseException ex) {
            Logger.getLogger(FrameIngresarFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    public FrameIngresarFactura() {
        
        initComponents();

        try {
            cargarDatos();
        } catch (ParseException ex) {
            Logger.getLogger(FrameIngresarFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }
    
    private void cargarDatos() throws ParseException{
        
        //Se crea un comboBox de objetos OrdenCompra
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        LogicaOrdenCompra logicaOrdenCompra = new LogicaOrdenCompra();
        
        for(OrdenCompra ordenCompra : logicaOrdenCompra.returnAllOrdenCompra()){
            model.addElement(ordenCompra);
        }
        this.comboBoxOrdenCompra.setModel(model);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBoxServicio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNumFactura = new javax.swing.JTextField();
        textCliente = new javax.swing.JTextField();
        textFechaEmision = new javax.swing.JTextField();
        textFechaPago = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        buttonIngresar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();
        buttonBorrar = new javax.swing.JButton();
        comboBoxOrdenCompra = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textMonto = new javax.swing.JTextField();
        buttonIngresarOrden = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número de Factura:");

        jLabel2.setText("Orden de Compra:");

        jLabel3.setText("Descripción:");

        jLabel4.setText("Cliente:");

        comboBoxServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", " " }));

        jLabel5.setText("Servicio:");

        jLabel6.setText("Fecha de Emisión:");

        jLabel7.setText("Fecha de Pago:");

        textNumFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumFacturaActionPerformed(evt);
            }
        });
        textNumFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textNumFacturaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNumFacturaKeyPressed(evt);
            }
        });

        textFechaEmision.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFechaEmisionFocusLost(evt);
            }
        });
        textFechaEmision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaEmisionActionPerformed(evt);
            }
        });
        textFechaEmision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFechaEmisionKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFechaEmisionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFechaEmisionKeyReleased(evt);
            }
        });

        textFechaPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFechaPagoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFechaPagoKeyReleased(evt);
            }
        });

        textDescripcion.setColumns(20);
        textDescripcion.setRows(5);
        jScrollPane1.setViewportView(textDescripcion);

        buttonIngresar.setText("Ingresar");
        buttonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIngresarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonBorrar.setText("Borrar Todo");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        jLabel8.setText("INGRESAR FACTURA");

        jLabel9.setText("Valor:");

        textMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMontoActionPerformed(evt);
            }
        });
        textMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textMontoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textMontoKeyReleased(evt);
            }
        });

        buttonIngresarOrden.setText("Ingresar Orden");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Orden de  Compra");

        jMenuItem1.setText("Ingresar Orden de Compra");
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textNumFactura)
                                            .addComponent(comboBoxOrdenCompra, 0, 155, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonIngresarOrden))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonBorrar)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel3)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(textFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(textFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(comboBoxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(textMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(textCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel8)))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxOrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonIngresarOrden))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(textFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIngresar)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonBorrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIngresarActionPerformed
        
        //Validar Campos
        if(this.comboBoxOrdenCompra.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "No ha asignado orden de compra.");
        }else
        {
        
            try {
                // TODO add your handling code here:
                LogicaFactura logicaFactura = new LogicaFactura();
                LogicaCliente logicaCliente = new LogicaCliente();


                Factura factura = new Factura();

                factura.setIdCliente(logicaCliente.returnCustomer(this.textCliente.getText()).getIdCliente());
                
                OrdenCompra orden = (OrdenCompra) this.comboBoxOrdenCompra.getSelectedItem();
                factura.setOrdenCompra(orden.getNumero());
                
                factura.setNumero(Integer.parseInt(this.textNumFactura.getText()));
                factura.setDescripcion(this.textDescripcion.getText());
                factura.setFechaEmision(this.textFechaEmision.getText());
                factura.setFechaPago(this.textFechaPago.getText());
                factura.setMonto(Integer.parseInt(this.textMonto.getText()));
                factura.setEstado("Ingresada");
                factura.setIdServicio(1);

                if(logicaFactura.ingresarFactura(factura))
                {
                    JOptionPane.showMessageDialog(null, "Se ha ingresado la factura");
                    borrarTodo();
                }else{
                    JOptionPane.showMessageDialog(null, "No se ha ingresado la factura.");
                }

                //
            } catch (SQLException ex) {
                Logger.getLogger(FrameIngresarFactura.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_buttonIngresarActionPerformed

    private void textMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMontoActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        // TODO add your handling code here:
        borrarTodo();
        
    }//GEN-LAST:event_buttonBorrarActionPerformed
    
    
    private void borrarTodo(){
        
        this.textCliente.setText("");
        this.textDescripcion.setText("");
        this.textFechaEmision.setText("");
        this.textFechaPago.setText("");
        this.textMonto.setText("");
        this.textNumFactura.setText("");
        this.comboBoxOrdenCompra.setSelectedIndex(0);
        this.comboBoxServicio.setSelectedIndex(0);
        
    }
    
    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        // TODO add your handling code here:  
        this.frameInicio.show();
        this.dispose();
        
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void textMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMontoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        //int num = (int) c;
        //JOptionPane.showMessageDialog(null, num);
        
        //Determina si el valor ingresar es numero, de no ser asi, consume el evento.
        if (((int)c<48) || ((int)c>57)){
            evt.consume();
        }
    }//GEN-LAST:event_textMontoKeyTyped

    public boolean isDate (String fecha){
        Pattern pat = null;
        Matcher mat = null;
        
        pat = Pattern.compile("##/##/##");
        mat = pat.matcher(fecha);
        
        if(mat.find()){
            return true;
        }else{
            return false;
        }  
    }
    
    
    
    private void textFechaEmisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaEmisionActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_textFechaEmisionActionPerformed

    private void textFechaEmisionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFechaEmisionFocusLost
        
    }//GEN-LAST:event_textFechaEmisionFocusLost

    private void textFechaEmisionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaEmisionKeyPressed
        
        
    }//GEN-LAST:event_textFechaEmisionKeyPressed

    private void textNumFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumFacturaActionPerformed
       
    }//GEN-LAST:event_textNumFacturaActionPerformed

    private void textNumFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumFacturaKeyPressed
        
    }//GEN-LAST:event_textNumFacturaKeyPressed

    private void textNumFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNumFacturaKeyTyped
        
        char c = evt.getKeyChar();
        //int num = (int) c;
        //JOptionPane.showMessageDialog(null, num);
        
        //Determina si el valor ingresar es numero, de no ser asi, consume el evento.
        if (((int)c<48) || ((int)c>57)){
            evt.consume();
        }
           
    }//GEN-LAST:event_textNumFacturaKeyTyped

    private void textFechaEmisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaEmisionKeyTyped
        
        char c = evt.getKeyChar();
        //int num = (int) c;
        //JOptionPane.showMessageDialog(null, num);
        
        //Determina si el valor ingresar es numero, de no ser asi, consume el evento.
        if (((int)c<48) || ((int)c>57) || this.textFechaEmision.getText().length() > 7){
            evt.consume();
            
        }
               
    }//GEN-LAST:event_textFechaEmisionKeyTyped

    private void textFechaPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaPagoKeyTyped
        char c = evt.getKeyChar();
        //int num = (int) c;
        //JOptionPane.showMessageDialog(null, num);
        
        //Determina si el valor ingresar es numero, de no ser asi, consume el evento.
        if (((int)c<48) || ((int)c>57) || this.textFechaPago.getText().length() > 7){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaPagoKeyTyped

    private void textFechaEmisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaEmisionKeyReleased
        char c = evt.getKeyChar();
        //int num = (int) c;
        //JOptionPane.showMessageDialog(null, num);
        
        //Validamos que el evento no es borrar.
        if (!((int)c == 8)){
                                       
        String p;
        //JOptionPane.showMessageDialog(null, this.textFechaEmision.getText().length() +"-" +(int)c+ "");
 
        switch (this.textFechaEmision.getText().length()) {
                
                case 2:
                    p = this.textFechaEmision.getText();
                        this.textFechaEmision.setText(p + "/");          
                break;
                
                case 3:
                    p = this.textFechaEmision.getText();
                    if(!p.contains("-")){
                        String p1 = p.substring(0, 2);
                        String p2 = p.substring(2);
                        this.textFechaEmision.setText(p1 + "/" + p2);  
                    }
                break;

                case 5:
                    p = this.textFechaEmision.getText();
                        this.textFechaEmision.setText(p + "/");
                break;
                
                case 6:
                    p = this.textFechaEmision.getText();
                    if(!p.contains("-")){
                        String p1 = p.substring(0, 5);
                        String p2 = p.substring(5);
                        this.textFechaEmision.setText(p1 + "/" + p2);  
                    }
                break;
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaEmisionKeyReleased

    private void textFechaPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFechaPagoKeyReleased
         // TODO add your handling code here:
        char c = evt.getKeyChar();
        //int num = (int) c;
        //JOptionPane.showMessageDialog(null, num);
        
        //Validamos que el evento no es borrar.
        if (!((int)c == 8)){
                                       
        String p;
        //JOptionPane.showMessageDialog(null, this.textFechaEmision.getText().length() +"-" +(int)c+ "");
 
        switch (this.textFechaPago.getText().length()) {
                
                case 2:
                    p = this.textFechaPago.getText();
                        this.textFechaPago.setText(p + "/");          
                break;
                
                case 3:
                    p = this.textFechaPago.getText();
                    if(!p.contains("-")){
                        String p1 = p.substring(0, 2);
                        String p2 = p.substring(2);
                        this.textFechaPago.setText(p1 + "/" + p2);  
                    }
                break;

                case 5:
                    p = this.textFechaPago.getText();
                        this.textFechaPago.setText(p + "/");
                break;
                
                case 6:
                    p = this.textFechaPago.getText();
                    if(!p.contains("-")){
                        String p1 = p.substring(0, 5);
                        String p2 = p.substring(5);
                        this.textFechaPago.setText(p1 + "/" + p2);  
                    }
                break;
            }
        } 
    }//GEN-LAST:event_textFechaPagoKeyReleased

    private void textMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textMontoKeyReleased
        // TODO add your handling code here:
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        //int num = (int) c;
        //JOptionPane.showMessageDialog(null, num);
        
        //Falta agregar los puntos ($222.333.444.555)
        
    }//GEN-LAST:event_textMontoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIngresarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIngresarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIngresarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIngresarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIngresarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonIngresar;
    private javax.swing.JButton buttonIngresarOrden;
    private javax.swing.JComboBox<String> comboBoxOrdenCompra;
    private javax.swing.JComboBox<String> comboBoxServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textCliente;
    private javax.swing.JTextArea textDescripcion;
    private javax.swing.JTextField textFechaEmision;
    private javax.swing.JTextField textFechaPago;
    private javax.swing.JTextField textMonto;
    private javax.swing.JTextField textNumFactura;
    // End of variables declaration//GEN-END:variables
}
