/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseño;

import persistencia.Usuario;

/**
 *
 * @author francoesteban
 */
public class FrameInicio extends javax.swing.JFrame {
    
    Usuario usuario;

    /**
     * Creates new form FrameInicio
     */
    public FrameInicio() {
        initComponents();
        
    }
    
    public FrameInicio(Usuario usuario) {
        
        initComponents();
        this.usuario = usuario;
        this.labelUsuario.setText(usuario.getNombres() + " " + usuario.getApellidoPaterno() + " " + usuario.getApellidoMaterno());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        labelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuFacturaIngresar = new javax.swing.JMenuItem();
        menuFacturaEditar = new javax.swing.JMenuItem();
        menuFacturaContabilizar = new javax.swing.JMenuItem();
        menuFacturaVer = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemConductoresRRHH = new javax.swing.JMenuItem();
        menInventario = new javax.swing.JMenu();
        menuVehiculos = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelUsuario.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        labelUsuario.setText("nombreUsuario");

        jMenu1.setText("File");

        MenuItemSalir.setText("Cerrar Sesión");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Facturas");

        menuFacturaIngresar.setText("Ingresar Factura");
        menuFacturaIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFacturaIngresarActionPerformed(evt);
            }
        });
        jMenu3.add(menuFacturaIngresar);

        menuFacturaEditar.setText("Editar Factura");
        menuFacturaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFacturaEditarActionPerformed(evt);
            }
        });
        jMenu3.add(menuFacturaEditar);

        menuFacturaContabilizar.setText("Contabilizar Factura");
        menuFacturaContabilizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFacturaContabilizarActionPerformed(evt);
            }
        });
        jMenu3.add(menuFacturaContabilizar);

        menuFacturaVer.setText("Ver Facturas");
        menuFacturaVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFacturaVerActionPerformed(evt);
            }
        });
        jMenu3.add(menuFacturaVer);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("RRHH");

        itemConductoresRRHH.setText("Conductores");
        jMenu4.add(itemConductoresRRHH);

        jMenuBar1.add(jMenu4);

        menInventario.setText("Inventario");
        jMenuBar1.add(menInventario);

        menuVehiculos.setText("Vehiculos");
        jMenuBar1.add(menuVehiculos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(429, Short.MAX_VALUE)
                .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        // TODO add your handling code here:
        FrameLogin frameLogin = new FrameLogin();
        frameLogin.show();
        this.dispose();
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void menuFacturaIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFacturaIngresarActionPerformed
        // TODO add your handling code here:
        FrameIngresarFactura frameIngresarFactura = new FrameIngresarFactura(this);
        frameIngresarFactura.show();
        this.dispose();
    }//GEN-LAST:event_menuFacturaIngresarActionPerformed

    private void menuFacturaContabilizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFacturaContabilizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFacturaContabilizarActionPerformed

    private void menuFacturaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFacturaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFacturaEditarActionPerformed

    private void menuFacturaVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFacturaVerActionPerformed
        // TODO add your handling code here:
        FrameFacturas frameVerFacturas = new FrameFacturas(this);
        frameVerFacturas.show();
        this.dispose();
    }//GEN-LAST:event_menuFacturaVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JMenuItem itemConductoresRRHH;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenu menInventario;
    private javax.swing.JMenuItem menuFacturaContabilizar;
    private javax.swing.JMenuItem menuFacturaEditar;
    private javax.swing.JMenuItem menuFacturaIngresar;
    private javax.swing.JMenuItem menuFacturaVer;
    private javax.swing.JMenu menuVehiculos;
    // End of variables declaration//GEN-END:variables
}
